[package]
name = "lmz"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.13", features = ["blocking", "json"] }
serde = { version = "1.0.148", features = ["derive"] }
confy = { version = "0.5.1" }
clap = { version = "4.0.29", features = ["derive", "cargo"] }
